--- a/Makefile	2026-09-12 12:46:24.693797694 +0000
+++ b/Makefile	2026-09-12 12:47:18.568249529 +0000
@@ -2,8 +2,8 @@
 
 ifneq ($(KERNELRELEASE),)
 
-obj-m += rtw89_core_git.o
-rtw89_core_git-y += core.o \
+obj-m += rtw89_core.o
+rtw89_core-y += core.o \
 		    mac80211.o \
 		    mac.o \
 		    mac_be.o \
@@ -21,115 +21,94 @@
 		    ser.o \
 		    acpi.o \
 		    util.o \
-		    debug.o \
-		    led.o \
-		    led_mc.o
+		    debug.o
 
-rtw89_core_git-$(CONFIG_PM) += wow.o
+rtw89_core-$(CONFIG_PM) += wow.o
 
-obj-m += rtw89_8851b_git.o
-rtw89_8851b_git-objs := rtw8851b.o \
+obj-m += rtw89_8851b.o
+rtw89_8851b-objs := rtw8851b.o \
 			rtw8851b_table.o \
 			rtw8851b_rfk.o \
 			rtw8851b_rfk_table.o
 
 ifneq ($(CONFIG_PCI),)
-obj-m += rtw89_8851be_git.o
-rtw89_8851be_git-objs := rtw8851be.o
+obj-m += rtw89_8851be.o
+rtw89_8851be-objs := rtw8851be.o
 endif
 
-obj-m += rtw89_8851bu_git.o
-rtw89_8851bu_git-objs := rtw8851bu.o
-
-obj-m += rtw89_8852a_git.o
-rtw89_8852a_git-objs := rtw8852a.o \
+obj-m += rtw89_8852a.o
+rtw89_8852a-objs := rtw8852a.o \
 			rtw8852a_table.o \
 			rtw8852a_rfk.o \
 			rtw8852a_rfk_table.o
 
 ifneq ($(CONFIG_PCI),)
-obj-m += rtw89_8852ae_git.o
-rtw89_8852ae_git-objs := rtw8852ae.o
+obj-m += rtw89_8852ae.o
+rtw89_8852ae-objs := rtw8852ae.o
 endif
 
-obj-m += rtw89_8852au_git.o
-rtw89_8852au_git-objs := rtw8852au.o
-
-obj-m += rtw89_8852b_common_git.o
-rtw89_8852b_common_git-objs := rtw8852b_common.o
+obj-m += rtw89_8852b_common.o
+rtw89_8852b_common-objs := rtw8852b_common.o
 
-obj-m += rtw89_8852b_git.o
-rtw89_8852b_git-objs := rtw8852b.o \
+obj-m += rtw89_8852b.o
+rtw89_8852b-objs := rtw8852b.o \
 			rtw8852b_table.o \
 			rtw8852b_rfk.o \
 			rtw8852b_rfk_table.o
 
 ifneq ($(CONFIG_PCI),)
-obj-m += rtw89_8852be_git.o
-rtw89_8852be_git-objs := rtw8852be.o
+obj-m += rtw89_8852be.o
+rtw89_8852be-objs := rtw8852be.o
 endif
 
-obj-m += rtw89_8852bu_git.o
-rtw89_8852bu_git-objs := rtw8852bu.o
-
 ifneq ($(CONFIG_PCI),)
-obj-m += rtw89_8852bt_git.o
-rtw89_8852bt_git-objs := rtw8852bt.o \
+obj-m += rtw89_8852bt.o
+rtw89_8852bt-objs := rtw8852bt.o \
 			 rtw8852bt_rfk.o \
 			 rtw8852bt_rfk_table.o
 endif
 
 ifneq ($(CONFIG_PCI),)
-obj-m += rtw89_8852bte_git.o
-rtw89_8852bte_git-objs := rtw8852bte.o
+obj-m += rtw89_8852bte.o
+rtw89_8852bte-objs := rtw8852bte.o
 endif
 
-obj-m += rtw89_8852c_git.o
-rtw89_8852c_git-objs := rtw8852c.o \
+obj-m += rtw89_8852c.o
+rtw89_8852c-objs := rtw8852c.o \
 			rtw8852c_table.o \
 			rtw8852c_rfk.o \
 			rtw8852c_rfk_table.o
 
 ifneq ($(CONFIG_PCI),)
-obj-m += rtw89_8852ce_git.o
-rtw89_8852ce_git-objs := rtw8852ce.o
+obj-m += rtw89_8852ce.o
+rtw89_8852ce-objs := rtw8852ce.o
 endif
 
-obj-m += rtw89_8852cu_git.o
-rtw89_8852cu_git-objs := rtw8852cu.o
-
-obj-m += rtw89_8922a_git.o
-rtw89_8922a_git-objs := rtw8922a.o \
+obj-m += rtw89_8922a.o
+rtw89_8922a-objs := rtw8922a.o \
 			rtw8922a_rfk.o
 
 ifneq ($(CONFIG_PCI),)
-obj-m += rtw89_8922ae_git.o
-rtw89_8922ae_git-objs := rtw8922ae.o
+obj-m += rtw89_8922ae.o
+rtw89_8922ae-objs := rtw8922ae.o
 endif
 
-obj-m += rtw89_8922au_git.o
-rtw89_8922au_git-objs := rtw8922au.o
-
 ifneq ($(CONFIG_PCI),)
-obj-m += rtw89_8922d_git.o
-rtw89_8922d_git-objs := rtw8922d.o \
+obj-m += rtw89_8922d.o
+rtw89_8922d-objs := rtw8922d.o \
 			rtw8922d_rfk.o
 
-obj-m += rtw89_8922de_git.o
-rtw89_8922de_git-objs := rtw8922de.o
+obj-m += rtw89_8922de.o
+rtw89_8922de-objs := rtw8922de.o
 endif
 
 ifneq ($(CONFIG_PCI),)
-obj-m += rtw89_pci_git.o
-rtw89_pci_git-y := pci.o pci_be.o
+obj-m += rtw89_pci.o
+rtw89_pci-y := pci.o pci_be.o
 endif
 
-obj-m += rtw89_usb_git.o
-rtw89_usb_git-y := usb.o
-
 ccflags-y += -Wno-compare-distinct-pointer-types
 ccflags-y += -DCONFIG_RTW89_DEBUGMSG -DCONFIG_RTW89_DEBUGFS
-ccflags-y += -DCONFIG_RTW89_LEDS -DCONFIG_RTW89_LEDS_MC
 ccflags-y += -DGIT_COMMIT=$(shell git --git-dir=$(src)/.git rev-parse HEAD)
 
 else
