--- a/Makefile
+++ b/Makefile
@@ -34,9 +34,6 @@
 obj-m += rtw89_8851be_git.o
 rtw89_8851be_git-objs := rtw8851be.o
 
-obj-m += rtw89_8851bu_git.o
-rtw89_8851bu_git-objs := rtw8851bu.o
-
 obj-m += rtw89_8852a_git.o
 rtw89_8852a_git-objs := rtw8852a.o \
 			rtw8852a_table.o \
@@ -46,9 +43,6 @@
 obj-m += rtw89_8852ae_git.o
 rtw89_8852ae_git-objs := rtw8852ae.o
 
-obj-m += rtw89_8852au_git.o
-rtw89_8852au_git-objs := rtw8852au.o
-
 obj-m += rtw89_8852b_common_git.o
 rtw89_8852b_common_git-objs := rtw8852b_common.o
 
@@ -61,9 +55,6 @@
 obj-m += rtw89_8852be_git.o
 rtw89_8852be_git-objs := rtw8852be.o
 
-obj-m += rtw89_8852bu_git.o
-rtw89_8852bu_git-objs := rtw8852bu.o
-
 obj-m += rtw89_8852bt_git.o
 rtw89_8852bt_git-objs := rtw8852bt.o \
 			 rtw8852bt_rfk.o \
@@ -81,9 +72,6 @@
 obj-m += rtw89_8852ce_git.o
 rtw89_8852ce_git-objs := rtw8852ce.o
 
-obj-m += rtw89_8852cu_git.o
-rtw89_8852cu_git-objs := rtw8852cu.o
-
 obj-m += rtw89_8922a_git.o
 rtw89_8922a_git-objs := rtw8922a.o \
 			rtw8922a_rfk.o
@@ -91,14 +79,8 @@
 obj-m += rtw89_8922ae_git.o
 rtw89_8922ae_git-objs := rtw8922ae.o
 
-obj-m += rtw89_8922au_git.o
-rtw89_8922au_git-objs := rtw8922au.o
-
 obj-m += rtw89_pci_git.o
 rtw89_pci_git-y := pci.o pci_be.o
-
-obj-m += rtw89_usb_git.o
-rtw89_usb_git-y := usb.o
 
 ccflags-y += -Wno-compare-distinct-pointer-types
 ccflags-y += -DCONFIG_RTW89_DEBUGMSG -DCONFIG_RTW89_DEBUGFS
