--- a/Makefile
+++ b/Makefile
@@ -165,4 +165,4 @@
 	KBUILD_NOPEDANTIC=1 make -C $(KBUILD_DIR) M=`pwd` clean
 
 install:
-	install -D -m 755 wl.ko $(MDEST_DIR)
+	install -D -m 755 wl.ko $(MDEST_DIR)/wl.ko
